# Generated by Django 3.2.5 on 2021-07-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0002_auto_20210728_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='per_unit_measure',
            field=models.CharField(choices=[('pc.', 'Pieces'), ('gr.', 'Grams'), ('eggs', 'Eggs'), ('ml.', 'Millilitres'), ('oz.', 'Ounces')], default='gr.', max_length=50),
        ),
    ]
