# Generated by Django 3.2.5 on 2021-07-29 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0003_alter_ingredient_per_unit_measure'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='menu_items_amount',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
