# Generated by Django 3.2.5 on 2021-07-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0004_purchase_menu_items_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='per_unit_measure',
            field=models.CharField(choices=[('pc.', 'Pieces'), ('gr.', 'Grams'), ('egg', 'Eggs'), ('ml.', 'Millilitres'), ('oz.', 'Ounces')], default='gr.', max_length=50),
        ),
    ]
