# Generated by Django 3.2.5 on 2021-08-01 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website_app', '0005_alter_ingredient_per_unit_measure'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='menu_items_amount',
        ),
        migrations.AlterField(
            model_name='reciperequirement',
            name='ingredient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recipe_requirements', to='website_app.ingredient'),
        ),
    ]
